Issue #311 create cl make bin stage
LSSTDESC/TXPipe pull request #314
Opened 2023-07-20 18:38 UTC by marina-ricci

In development, linked to #311 and #309

2023-10-17 13:42 UTC, marina-ricci commented
Pipeline and config files are also written to run the CL pipeline,

 as well as the batch script for CCin2p3 and

- notebook running the pipeline and exploring the input and output files : 
[Run_CL_pipeline](https://github.com/LSSTDESC/TXPipe/blob/issue_%23311_create_CL_make_bin_stage/notebooks/Run_CL_pipeline.ipynb
)

2023-10-18 17:49 UTC, marina-ricci commented
@cavestruz : the PR is ready on my side. Normally you should have all info from the notebook! Please test the nersc launcher (just for the 1deg2 should be sufficient) as I did not test it. We should find better way to work at the two site with changing just the launcher file, but I did not find the proper way to do it. So you also have to change the first lines in the pipeline files.

2023-10-19 15:56 UTC, cavestruz requested changes
Primary changes are to change the 20sqdeg yaml files so this works.

2023-10-19 15:56 UTC, cavestruz commented on examples/cosmodc2/pipeline-20deg2-CL-nersc.yml
- [ ] This has some lines that need updating to run, consistent with the 1deg2 version.

2023-10-19 15:56 UTC, cavestruz commented on examples/cosmodc2/pipeline-20deg2-CL-in2p3.yml
- [ ] This has some lines that need updating to run, consistent with the 1deg2 version.

2023-10-19 15:56 UTC, cavestruz commented on notebooks/Run_CL_pipeline.ipynb
I made some minor additions here to account for different in2p3 vs. nersc files.

2023-10-19 15:56 UTC, cavestruz commented on examples/cosmodc2/config-20deg2-CL.yml
Made minor change here, so there are separate yaml files depending on where the user is running the notebook.

2023-10-19 18:49 UTC, marina-ricci commented
@cavestruz : I did some cleaning as there were typos in the files and reorganized the notebook to clarify the 2 approaches to run : direclty from jupyter or via pipeline/ceci. I commented all unused stages / input so that the pipeline chart for this PR is just:
![image](https://github.com/LSSTDESC/TXPipe/assets/45492897/90bb9b2a-4162-4946-9cda-b8692d05aa8f)

2023-10-19 19:27 UTC, cavestruz approved these changes
Great - I am able to run everything in the notebook, and submit the `sbatch examples/cosmodc2/20deg2-nersc.sub` to run the tail end of cells in `Run_CL_counts_pipeline.ipynb`.

2023-10-19 19:27 UTC, cavestruz commented on examples/cosmodc2/config-20deg2-CL.yml
Testing this out now with the `squeue` submission.  Will then check if latter portion of notebook runs on NERSC with the output of the 20deg2 submission that uses this yaml file.

2023-10-19 19:27 UTC, merged