Lf calibration
LSSTDESC/TXPipe pull request #346
Opened 2024-04-12 16:16 UTC by jmjefferson

Unifies calibrations for mainly KiDS' catalogs, also makes an option to convert psf units from pixels to arcseconds. In addition, unifying metacal calibrations in specifically the psf diagnostics file.

2024-04-15 14:17 UTC, yomori requested changes
various changes

2024-04-15 14:17 UTC, yomori commented on txpipe/utils/calibration_tools.py
> +            x = x * 0.214**2
Again should probably make this an option in the config file

2024-04-15 14:17 UTC, yomori commented on txpipe/utils/calibrators.py
> +            Nmask = dec > -25.0
Perhaps we can make this split dec an option as well? Then if someone for some reason wants to revert to analyzing everything at once they can just set this dec cut to like -90 or something.

2024-04-16 02:46 UTC, jmjefferson commented on txpipe/test/test_cal_lensfit.py
> +        "dec": np.random.normal(-5, 4, size=8),
nah it runs this test data thru the mean shear code, so for lensift it needs the dec to do the field splitting

2024-04-16 02:49 UTC, jmjefferson commented on txpipe/test/test_cal_lensfit.py
> +        "dec": np.random.normal(-5, 4, size=8),
so I just fed in the approximate dec bounds for the north field

2024-04-16 17:35 UTC, jmjefferson commented
the galaxy star shear stage works for me using the actual lensfit data--I'm not sure why it isn't working in the check

2024-04-26 14:48 UTC, elvinpoole requested changes
Looks good to me. My only comment is we should probably make `dec_cut` a config option in the source selector stage. just to make it easy for us if we want to switch it off for a given run

2024-05-07 14:41 UTC, yomori approved these changes

2024-05-07 16:25 UTC, elvinpoole approved these changes

2024-05-07 16:26 UTC, merged