SSI DES inputs
LSSTDESC/TXPipe pull request #358
Opened 2024-07-05 15:54 UTC by elvinpoole

2024-09-20 15:54 UTC, elvinpoole commented on txpipe/lens_selector.py
To get the DES maglim selection from Balrog catalogs, I included the EXTENDED_CLASS_SOF (the star galaxy separator) and FLAGS_GOLD columns. 

Alternatively, we could rename these columns in the ingestion stage to something more Rubin-like and use these. Depends on how generic we want the lens selector options to be

2024-09-20 18:10 UTC, joezuntz requested changes
Looks good - just some minor requests.

2024-10-09 19:55 UTC, elvinpoole commented on txpipe/ingest/ssi.py
> +        column_names = {
done

2024-10-09 19:57 UTC, elvinpoole commented on txpipe/ingest/ssi.py
> +                    #TO DO: compute mag errors from flux errors
since the maglim selection doesn't use these errors, l'm inclined to leave this as a TODO for now

2024-10-09 20:00 UTC, elvinpoole commented on txpipe/lens_selector.py
> +        cut4 = (np.bitwise_and(flags,120) == 0) #flags
done. Also updated value to 126 which is the correct value. it selects the first 6 bits out of 7 which is the fixed definition for the DES maglim selection. when we add flag cuts for a DESC lens selection we should make this an input param

2024-10-10 08:32 UTC, joezuntz commented on txpipe/ingest/ssi.py
> +                    #TO DO: compute mag errors from flux errors
Yep, that's fine.

2024-10-11 16:29 UTC, joezuntz approved these changes

2024-10-11 16:29 UTC, merged