Cluster clustering measurement code
LSSTDESC/TXPipe pull request #377
Opened 2024-11-28 15:36 UTC by AlessandraFumagalli

Wrote code for measuring 2D two-point correlation function of clusters, in richness bins. 
Wrote notebook to test the code and validate it against and external code.

2025-02-10 13:35 UTC, joezuntz requested changes
Looks goof in general - see notes below for requested changes.

2025-02-10 13:35 UTC, joezuntz commented on examples/clustering_test/config/config_clusters.yml
Could you give the directory here ("clustering_test") a slightly more specific name?

2025-02-10 13:35 UTC, joezuntz commented on examples/clustering_test/outputs/test/cluster_twopoint_real.sacc
If this is an output file then you also don't want to include it I think?

2025-02-10 13:35 UTC, joezuntz commented on txpipe/__init__.py
> +from .twopoint_cluster import TXTwoPointCluster
If we move the twopoint_cluster file (see comment below) then you should also change this.

2025-02-10 13:35 UTC, joezuntz commented on txpipe/twopoint_cluster.py
> +            s.add_tracer('NZ', tracer1, np.array([1]), np.array([1]))
Is this just a placeholder? You can also use a "misc" tracer for this. I think each tracer here is a richness/redshift bin - is that right?  We might want to find a way to represent that.

2025-02-28 14:52 UTC, AlessandraFumagalli commented on txpipe/__init__.py
> +from .twopoint_cluster import TXTwoPointCluster
Not clear what is the "comment below".
Where should I move the twopoint_cluster file?

2025-04-15 09:25 UTC, joezuntz reviewed
I've mentioned the only two things I'd like you to do from a repo tidiness point of view.  Would it be useful for me to do a more thorough (code and scientific) review for you or would you just like to manage that internally within the CL group?  This is all in a subdirectory so I'm happy either way, as long as nothing breaks the main code.

2025-04-15 09:25 UTC, joezuntz commented on examples/twopoint_cluster/TXTwoPointCluster.out
> +Executing stage: TXTwoPointCluster @ 2025-01-13 17:35:10.802489
Can you remove this file from the PR?

2025-04-15 09:25 UTC, joezuntz commented on examples/twopoint_cluster/outputs/test/cluster_twopoint_real.sacc
This file should also be removed from the PR

2025-04-22 15:02 UTC, joezuntz commented on txpipe/extensions/twopoint_cluster.py~
Sorry - I think I missed this one last time - it's an empty ~ file left over by an editor - can you delete?

2025-04-22 15:05 UTC, joezuntz commented on txpipe/extensions/twopoint_cluster.py~
Actually never mind, I can delete it.

2025-04-22 15:06 UTC, joezuntz commented on txpipe/extensions/twopoint_cluster.py
> +from txpipe.base_stage import PipelineStage
The right syntax for importing from a different sub-package is to use a relative import:

```
from ..base_stage import PipelineStage
from ..data_types import HDFFile, SACCFile
```

I have updated this.

2025-04-22 15:08 UTC, joezuntz commented
I've made some small tweaks to this and now can merge it once the tests are run.

2025-04-23 08:41 UTC, joezuntz approved these changes

2025-04-23 08:42 UTC, merged